gaps:
  inner_gap: 10
  outer_gap: 10
general:
  show_floating_on_top: false
  cursor_follows_focus: false
  floating_window_move_amount: "100px"
bar:
  height: "20px"
  position: "top"
  opacity: 1.0
  background: "#20242cc4"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "0px 6px"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_right:
    - type: "tiling direction"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "clock"
      time_formatting: "hh:mm tt  ddd MMM d"
      margin: "0 0 0 10px"
workspaces:
  - name: "editor"
    keep_alive: true
  - name: "browser"
    keep_alive: true
  - name: "im"
    keep_alive: true
  - name: "terminal"
    keep_alive: true
  - name: "doc"
    keep_alive: true

window_rules:
  - command: "move to workspace browser"
    match_process_name: "chrome"
  - command: "move to workspace editor"
    match_process_name: "wezterm-gui"
  - command: "set floating"
    match_class_name: "#32770"

binding_modes:
  - name: "launch"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - commands: ["exec cmd.exe", "binding mode none"]
        bindings: ["SUI_S打开"]
      - commands: ["exec cmd.exe", "binding mode none"]
        bindings: ["Control+L"]
      - commands: ["exec %USERPROFILE%/AppData/Local/Programs/utools/uTools.exe", "binding mode none"]
        bindings: ["W"]
      - commands: ["exec %USERPROFILE%/AppData/Local/Programs/utools/uTools.exe", "binding mode none"]
        bindings: ["F"]
      - commands: ["tiling direction horizontal", "binding mode none", "exec %USERPROFILE%/AppData/Local/Programs/utools/uTools.exe"]
        bindings: ["V"]
      - commands: ["tiling direction vertical", "binding mode none", "exec %USERPROFILE%/AppData/Local/Programs/utools/uTools.exe"]
        bindings: ["H"]
      - commands: ["reload config", "binding mode none"]
        binding: "R"
      - commands: ["reload config", "binding mode none"]
        binding: "C"
      - commands: ["exec cmd.exe", "binding mode none"]
        binding: "Alt+C"
  - name: "quit"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - commands: ["close", "binding mode none"]
        binding: "SUI_S关闭"
      - commands: ["close", "binding mode none"]
        binding: "SUI_S标签"
      - commands: ["close", "binding mode none"]
        binding: "SUI_S窗口"
      - commands: ["exit wm"]
        binding: "A"
  - name: "goto"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - commands: ["exec cmd.exe", "binding mode none"]
        binding: "T"
  - name: "size"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - command: "resize height +2%"
        bindings: ["SUI_S小上", "Up"]
      - command: "resize height -2%"
        bindings: ["SUI_S小下", "Down"]
      - command: "resize width -2%"
        bindings: ["SUI_S小左", "Left"]
      - command: "resize width +2%"
        bindings: ["SUI_S小右", "Right"]
      - commands: ["toggle maximized", "binding mode none"]
        bindings: ["M"]
      - commands: ["toggle maximized", "binding mode none"]
        bindings: ["Z"]
      - commands: ["set minimized", "binding mode none"]
        bindings: ["H"]
      - commands: ["binding mode none", "exec python %SUI_ROOT%/sui/not_implement.py"]
        bindings: ["W"]
      - commands: ["binding mode none"]
        bindings: ["T"]
  - name: "move"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - commands: ["move left", "binding mode none"]
        bindings: ["SUI_S小左"]
      - commands: ["move right", "binding mode none"]
        bindings: ["SUI_S小右"]
      - commands: ["move up", "binding mode none"]
        bindings: ["SUI_S小上"]
      - commands: ["move down", "binding mode none"]
        bindings: ["SUI_S小下"]
      - commands: ["move workspace left", "binding mode none"]
        bindings: ["Left"]
      - commands: ["move workspace right", "binding mode none"]
        bindings: ["Right"]
      - commands: ["toggle floating", "binding mode none"]
        bindings: ["F"]
      - commands: ["set floating", "binding mode none"]
        bindings: ["Shift+F"]
  - name: "tabto"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - commands: ["focus workspace editor", "binding mode none"]
        bindings: ["E"]
      - commands: ["focus workspace browser", "binding mode none"]
        bindings: ["B"]
      - commands: ["focus workspace terminal", "binding mode none"]
        bindings: ["T"]
      - commands: ["focus workspace im", "binding mode none"]
        bindings: ["I"]
      - commands: ["focus workspace doc", "binding mode none"]
        bindings: ["D"]
  - name: "arrive"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - commands: ["move to workspace editor","focus workspace editor", "binding mode none"]
        bindings: ["E"]
      - commands: ["move to workspace browser","focus workspace browser", "binding mode none"]
        bindings: ["B"]
      - commands: ["move to workspace terminal","focus workspace terminal", "binding mode none"]
        bindings: ["T"]
      - commands: ["move to workspace im","focus workspace im", "binding mode none"]
        bindings: ["I"]
      - commands: ["move to workspace doc","focus workspace doc", "binding mode none"]
        bindings: ["D"]
      - commands: ["move to workspace editor", "binding mode none"]
        bindings: ["Shift+E"]
      - commands: ["move to workspace browser", "binding mode none"]
        bindings: ["Shift+B"]
      - commands: ["move to workspace terminal", "binding mode none"]
        bindings: ["Shift+T"]
      - commands: ["move to workspace im", "binding mode none"]
        bindings: ["Shift+I"]
      - commands: ["move to workspace doc", "binding mode none"]
        bindings: ["Shift+D"]
  - name: "goto"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape"]
      - command: "binding mode none"
        bindings: ["Control+OemOpenBrackets"]
      - commands: ["focus workspace recent", "binding mode none"]
        bindings: ["SUI_S小左"]
      - commands: ["focus workspace recent", "binding mode none"]
        bindings: ["SUI_S小右"]
      - commands: ["binding mode none", "exec %SUI_ROOT%/sui/not_implement.bat"]
        bindings: ["."]
keybindings:
  - command: "binding mode launch"
    binding: "Control+SUI_S打开"
  - command: "binding mode quit"
    binding: "Control+SUI_S关闭"
  - command: "binding mode goto"
    binding: "Control+SUI_S直跳"
  - command: "binding mode move"
    binding: "Control+SUI_S移动"
  - command: "binding mode size"
    binding: "Control+SUI_S大小"
  - command: "binding mode arrive"
    binding: "Control+SUI_S去到标签"
  - command: "binding mode tabto"
    binding: "Control+SUI_S跳转"
  - commands: ["focus left"]
    bindings: ["Control+SUI_S小左"]
  - commands: ["focus right"]
    bindings: ["Control+SUI_S小右"]
  - commands: ["focus up"]
    bindings: ["Control+SUI_S小上"]
  - commands: ["focus down"]
    bindings: ["Control+SUI_S小下"]
  - commands: ["focus workspace prev"]
    bindings: ["Control+F3"]
  - commands: ["focus workspace next"]
    bindings: ["Control+F2"]
  - commands: ["toggle focus mode"]
    bindings: ["Control+K"]
  - commands: ["toggle focus mode"]
    bindings: ["Control+Down"]
  - commands: ["toggle focus mode"]
    bindings: ["Control+Up"]
